// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookStore.API.ViewModels.Post
{
    public partial class CreateAspNetUserVM
    {
        [StringLength(50)]
        [Required(ErrorMessage = "First name is required!")]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Last name is required!")]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Othernames { get; set; }
        [Required(ErrorMessage = "Address is required!")]
        public string Address { get; set; }

        [StringLength(256)]
        [Required(ErrorMessage = "Name is required!")]
        public string Email { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}