// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace BookStore.API.ViewModels.Post
{
    public partial class CreateBookVM
    {
        [JsonIgnore]
        public string Id { get; set; } = Guid.NewGuid().ToString();
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(150)]
        public string Author { get; set; }
        [StringLength(150)]
        public string Description { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? UnitCost { get; set; }
        [StringLength(150)]
        public string ImageUrl { get; set; }
        [StringLength(150)]
        public string DownloadUrl { get; set; }
    }
}