// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookStore.API.ViewModels.Get
{
    public partial class AspNetUserVM
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Othernames { get; set; }
        public string Address { get; set; }
        public bool? IsDeleted { get; set; }
        [StringLength(256)]
        public string UserName { get; set; }
        [StringLength(256)]
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public DateTimeOffset? LockoutEnd { get; set; }
        public int AccessFailedCount { get; set; }

       
        public virtual ICollection<AspNetUserClaimVM> AspNetUserClaims { get; set; }
       
        public virtual ICollection<AspNetUserLoginVM> AspNetUserLogins { get; set; }
       
        public virtual ICollection<AspNetUserTokenVM> AspNetUserTokens { get; set; }
       
        public virtual ICollection<BookVM> Books { get; set; }
       
        public virtual ICollection<CartVM> Carts { get; set; }
        public virtual ICollection<ReviewVM> Reviews { get; set; }
        public virtual ICollection<TransactionVM> Transactions { get; set; }
        public virtual ICollection<WalletVM> Wallets { get; set; }

        public virtual ICollection<AspNetRoleVM> Roles { get; set; }
    }
}