// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookStore.API.ViewModels.Get
{
    public partial class ReviewVM
    {
        [Key]
        public string Id { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(450)]
        public string BookId { get; set; }
        public int? Weight { get; set; }
        [StringLength(150)]
        public string Description { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        public DateTime? DateCreated { get; set; }
        public virtual AspNetUserVM User { get; set; }
        public virtual BookVM UserNavigation { get; set; }
    }
}