// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace BookStore.DAL.Models
{
    public partial class AspNetUser : IdentityUser
    {
        public AspNetUser()
        {
            Books = new HashSet<Book>();
            Carts = new HashSet<Cart>();
            Reviews = new HashSet<Review>();
            Transactions = new HashSet<Transaction>();
            Wallets = new HashSet<Wallet>();
        }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(50)]
        public string Othernames { get; set; }
        public string Address { get; set; }
        public bool? IsDeleted { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Book> Books { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Cart> Carts { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Review> Reviews { get; set; }
        [InverseProperty("CreatedByNavigation")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Wallet> Wallets { get; set; }
    }
}