// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookStore.DAL.Models
{
    public partial class Book
    {
        public Book()
        {
            CartItems = new HashSet<CartItem>();
            Reviews = new HashSet<Review>();
        }

        [Key]
        public string Id { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(150)]
        public string Author { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? UnitCost { get; set; }
        [StringLength(150)]
        public string Description { get; set; }
        [StringLength(150)]
        public string ImageUrl { get; set; }
        [StringLength(150)]
        public string DownloadUrl { get; set; }
        [StringLength(450)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }
        [StringLength(450)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateModified { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Books")]
        public virtual AspNetUser User { get; set; }
        [InverseProperty("Book")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        [InverseProperty("UserNavigation")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}