// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookStore.DAL.Models
{
    public partial class Review
    {
        [Key]
        public string Id { get; set; }
        [StringLength(450)]
        public string UserId { get; set; }
        [StringLength(450)]
        public string BookId { get; set; }
        [StringLength(150)]
        public string Description { get; set; }
        public int? Weight { get; set; }
        [StringLength(20)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateCreated { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Reviews")]
        public virtual AspNetUser User { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("Reviews")]
        public virtual Book UserNavigation { get; set; }
    }
}